/**
 * Custom Chat Agent - TypeScript Implementation
 * This demonstrates how to create a custom agent with code-behind
 */

export const chatHandler = async ({ input, variables, context }) => {
    // Full TypeScript power available here
    context.log("Processing chat message with custom TypeScript logic");

    const message = input.message || "";
    const history = input.messages || [];

    // Add user message to history
    history.push({ role: "user", content: message });

    // Simple echo response (in a real implementation, you could call external APIs, use Beddel helpers, etc.)
    const response = `Custom agent received: "${message}". This response was generated by TypeScript code!`;

    // Add assistant response to history
    history.push({ role: "assistant", content: response });

    context.log(`Custom chat handler processed message successfully`);

    return {
        response,
        history,
        timestamp: new Date().toISOString(),
        processed: true
    };
};
